### ISSUE TITLE
Binary is saved as txt file

### ISSUE THREAD

**Issue by Loggan08** [LoLUpdater/LoLUpdater-macOS#6]
<img width="1982" alt="skarmavbild 2017-02-21 kl 20 03 26" src="https://cloud.githubusercontent.com/assets/7104301/23182027/677bbb2c-f877-11e6-8136-b555927b639f.png">

OSX 10.12.3

**Comment by davidkna** [comment]
What browser did you use to download this?
Can't reproduce and for the download MIME type is set correctly to `application/octet-stream` (binary file) by Github.

**Comment by davidkna** [comment]
Actually I only tested this with curl on Linux. I could reproduce the issues on MacOS.
I'm redistributing this binary in a `tar.gz` archive now wish should work fine.

**Comment by aiiDaH** [comment]
Hello i used safari browser and double clicked and a text filé opened again so i tried to open the file with Python launcher and then it worked a terminal Window openened and adobe air started to download and later on it sad all suscsefull so i hope all is correct installed for me.

Skickat från min iPhone

23 feb. 2017 kl. 16:55 skrev David Knaack <notifications@github.com<mailto:notifications@github.com>>:


Actually I only tested this with curl on Linux. I could reproduce the issues on MacOS.
I'm redistributing this binary in a tar.gz archive now wish should work fine.

**Comment by davidkna** [comment]
This should be fine. But you don't need the Python launcher - it can be run from Terminal.app directly and doesn't have any dependency on Python anymore.
Also with the new download you can just double-click it if you don't need to add any of the command line arguments outlined in the README.

**Comment by aiiDaH** [comment]
Okey Perfect, where is the new download filé i can try?

Skickat från min iPhone

23 feb. 2017 kl. 21:50 skrev David Knaack <notifications@github.com<mailto:notifications@github.com>>:


This should be fine. But you don't need the Python launcher - it can be run from Terminal.app directly and doesn't have any dependency on Python anymore.
Also with the new download you can just double-click it if you don't need to add any of the command line arguments outlined in the README.

**Comment by Loggan08** [comment]
https://github.com/LoLUpdater/LoLUpdater-macOS/releases/download/v3.1.1/lolupdater.tar.gz
