### ISSUE TITLE
Unable to install on Sierra

### ISSUE THREAD

**Issue by Loggan08** [LoLUpdater/LoLUpdater-macOS#7]
"Hi, I tried to install the program, but when I opened the zip file I could not run it since my Mac told me the file is faulty? I've tried reinstalling etc. but to no avail.

Thanks."

**Comment by Loggan08** [comment]
I think he attempted to install Windows version of LoLUpdater on Mac, I told him about it.

**Comment by davidkna** [comment]
Will check this out on the weekend.
Just to make sure: This wasn't gatekeeper error and you downloaded the `lolupdater.tar.gz` (empasis on tar.gz) file?
